
version: "3.7"
services:
   main_service:
     image: josephigbi/service-1
     build: ./service1
     ports:
     - target: 5000
       published: 5001
     environment: 
     - API_KEY=${API_KEY} 
     - SECRET_KEY=${SECRET_KEY}
     - DATABASE_URI2=${DATABASE_URI2}

   service2:
     image: josephigbi/service-2
     build: ./service2
     ports:
     - target: 5000
     environment:
     - API_KEY=${API_KEY} 
     - SECRET_KEY=${SECRET_KEY}
     - DATABASE_URI2=${DATABASE_URI2}

   service3:
     image: josephigbi/service-3
     build: ./service3
     ports:
     - target: 5000
     environment: 
     - API_KEY=${API_KEY} 
     - SECRET_KEY=${SECRET_KEY}
     - DATABASE_URI2=${DATABASE_URI2}

   service4:
     image: josephigbi/service-4
     build: ./service4
     ports:
     - target: 5000
     environment: 
     - API_KEY=${API_KEY} 
     - SECRET_KEY=${SECRET_KEY}
     - DATABASE_URI2=${DATABASE_URI2}

   database:
     image: mysql:5.7
     ports:
     - target: 3306
       published: 3306       
     environment: 
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_DATABASE=${MYSQL_DATABASE}




