
version: "3.7"
services:
   main_service:
     image: josephigbi 
     build: ./service1
     ports:
     - target: 5000
       published: 5001
     environment: 
     - SECRET_KEY="7218a9143c27c16610765205a1b21cb7"
     - DATABASE_URI2=mysql+pymysql://root:admin@database/flask2

   service2:
     image: josephigbi 
     build: ./service2
     ports:
     - target: 5000
     environment: 
     - SECRET_KEY="7218a9143c27c16610765205a1b21cb7"
     - DATABASE_URI2=mysql+pymysql://root:admin@database/flask2

   service3:
     image: josephigbi
     build: ./service3
     ports:
     - target: 5000
     environment: 
     - SECRET_KEY="7218a9143c27c16610765205a1b21cb7"
     - DATABASE_URI2=mysql+pymysql://root:admin@database/flask2

   service4:
     image: josephigbi 
     build: ./service4
     ports:
     - target: 5000
     environment: 
     - SECRET_KEY="7218a9143c27c16610765205a1b21cb7"
     - DATABASE_URI2=mysql+pymysql://root:admin@database/flask2


   database:
     image: mysql:5.7
     ports:
     - target: 3306
       published: 3306       
     environment: 
     - MYSQL_ROOT_PASSWORD=admin
     - MYSQL_DATABASE=flask2




